spring:
  config:
    import: optional:file:.env[.properties]
  data:
    redis:
      port: ${REDIS_PORT:6379}
      host: ${REDIS_HOST:localhost}
      timeout: 2000
      connect-timeout: 2000
      repositories:
        enabled: false
      lettuce:
        pool:
          max-active: 5
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_URL:localhost:9092}
    listener:
      ack-mode: manual
      concurrency: 3
    consumer:
      group-id: identity-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        "spring.json.trusted.packages": "*"
    producer:
      acks: all
      retries: 10
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        "[enable.idempotence]": true
        "[max.in.flight.requests.per.connection]": 5
  datasource:
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:12345}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME}
    hikari:
      maximum-pool-size: 150
      minimum-idle: 50
      idle-timeout: 30000
      connection-timeout: 2000
      max-lifetime: 180000
      validation-timeout: 1000
      pool-name: vns-identity
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jackson:
    serialization:
      flush-after-write-value: true
    default-property-inclusion: non_null

server:
  servlet:
    context-path: /api/v1
  port: 8080

security:
  jwt:
    private-key-path: ${SECURITY_JWT_PRIVATE_KEY_PATH:./keys/jwt-private.pem}
    public-key-path: ${SECURITY_JWT_PUBLIC_KEY_PATH:./keys/jwt-public.pem}
    key-id: ${SECURITY_JWT_KEY_ID:identity-key-1}
    issuer: ${SECURITY_JWT_ISSUER:vietnamsea-identity}
    max-age: ${SECURITY_JWT_MAX_AGE:3600}
  oauth2:
    master-key: ${OAUTH_MASTER_KEY:123456}

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    try-it-out-enabled: true
    operations-sorter: method
    tags-sorter: alpha
    filter: true
    path: /swagger-ui

logging:
  level:
    root: WARN
    "[org.vietnamsea.identity]": INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
