// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: media_files.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countOwnedMediaFiles = `-- name: CountOwnedMediaFiles :one
SELECT COUNT(*)
FROM media_owners
WHERE owner_type = $1
  AND owner_id = $2
`

type CountOwnedMediaFilesParams struct {
	OwnerType string
	OwnerID   uuid.UUID
}

func (q *Queries) CountOwnedMediaFiles(ctx context.Context, arg CountOwnedMediaFilesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOwnedMediaFiles, arg.OwnerType, arg.OwnerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMediaFile = `-- name: CreateMediaFile :one
INSERT INTO media_files (
    file_name,
    mime_type,
    size,
    checksum,
    status,
    uploaded_by,
    original_name,
    duration_ms
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING
    id,
    file_name,
    mime_type,
    size,
    checksum,
    status,
    uploaded_by,
    original_name,
    duration_ms,
    created_at
`

type CreateMediaFileParams struct {
	FileName     string
	MimeType     string
	Size         int64
	Checksum     pgtype.Text
	Status       string
	UploadedBy   pgtype.UUID
	OriginalName pgtype.Text
	DurationMs   pgtype.Int4
}

func (q *Queries) CreateMediaFile(ctx context.Context, arg CreateMediaFileParams) (MediaFile, error) {
	row := q.db.QueryRow(ctx, createMediaFile,
		arg.FileName,
		arg.MimeType,
		arg.Size,
		arg.Checksum,
		arg.Status,
		arg.UploadedBy,
		arg.OriginalName,
		arg.DurationMs,
	)
	var i MediaFile
	err := row.Scan(
		&i.ID,
		&i.FileName,
		&i.MimeType,
		&i.Size,
		&i.Checksum,
		&i.Status,
		&i.UploadedBy,
		&i.OriginalName,
		&i.DurationMs,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMediaFile = `-- name: DeleteMediaFile :exec
DELETE FROM media_files
WHERE id = $1
`

func (q *Queries) DeleteMediaFile(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMediaFile, id)
	return err
}

const getMediaFileByID = `-- name: GetMediaFileByID :one
SELECT
    id,
    file_name,
    mime_type,
    size,
    checksum,
    status,
    uploaded_by,
    original_name,
    duration_ms,
    created_at
FROM media_files
WHERE id = $1
`

func (q *Queries) GetMediaFileByID(ctx context.Context, id uuid.UUID) (MediaFile, error) {
	row := q.db.QueryRow(ctx, getMediaFileByID, id)
	var i MediaFile
	err := row.Scan(
		&i.ID,
		&i.FileName,
		&i.MimeType,
		&i.Size,
		&i.Checksum,
		&i.Status,
		&i.UploadedBy,
		&i.OriginalName,
		&i.DurationMs,
		&i.CreatedAt,
	)
	return i, err
}

const getMediaFileDetailByID = `-- name: GetMediaFileDetailByID :one
SELECT
    mf.id,
    mf.file_name,
    mf.mime_type,
    mf.size,
    mf.checksum,
    mf.status,
    mf.uploaded_by,
    mf.original_name,
    mf.duration_ms,
    mf.created_at,
    policy.visibility,
    primary_object.id AS primary_storage_object_id,
    primary_object.storage_key AS primary_storage_key,
    primary_provider.id AS primary_storage_provider_id,
    primary_provider.name AS primary_storage_provider_name,
    primary_provider.provider_type AS primary_provider_type,
    primary_provider.bucket AS primary_bucket,
    primary_provider.region AS primary_region,
    primary_provider.endpoint AS primary_endpoint
FROM media_files AS mf
LEFT JOIN LATERAL (
    SELECT
        map.visibility
    FROM media_access_policies AS map
    WHERE map.media_id = mf.id
    ORDER BY map.created_at DESC
    LIMIT 1
) AS policy ON TRUE
LEFT JOIN LATERAL (
    SELECT
        mso.id,
        mso.storage_provider_id,
        mso.storage_key
    FROM media_storage_objects AS mso
    WHERE mso.media_id = mf.id
      AND mso.is_primary = TRUE
    ORDER BY mso.created_at DESC
    LIMIT 1
) AS primary_object ON TRUE
LEFT JOIN storage_providers AS primary_provider
    ON primary_provider.id = primary_object.storage_provider_id
WHERE mf.id = $1
`

type GetMediaFileDetailByIDRow struct {
	ID                         uuid.UUID
	FileName                   string
	MimeType                   string
	Size                       int64
	Checksum                   pgtype.Text
	Status                     string
	UploadedBy                 pgtype.UUID
	OriginalName               pgtype.Text
	DurationMs                 pgtype.Int4
	CreatedAt                  pgtype.Timestamptz
	Visibility                 string
	PrimaryStorageObjectID     uuid.UUID
	PrimaryStorageKey          string
	PrimaryStorageProviderID   pgtype.UUID
	PrimaryStorageProviderName pgtype.Text
	PrimaryProviderType        pgtype.Text
	PrimaryBucket              pgtype.Text
	PrimaryRegion              pgtype.Text
	PrimaryEndpoint            pgtype.Text
}

func (q *Queries) GetMediaFileDetailByID(ctx context.Context, id uuid.UUID) (GetMediaFileDetailByIDRow, error) {
	row := q.db.QueryRow(ctx, getMediaFileDetailByID, id)
	var i GetMediaFileDetailByIDRow
	err := row.Scan(
		&i.ID,
		&i.FileName,
		&i.MimeType,
		&i.Size,
		&i.Checksum,
		&i.Status,
		&i.UploadedBy,
		&i.OriginalName,
		&i.DurationMs,
		&i.CreatedAt,
		&i.Visibility,
		&i.PrimaryStorageObjectID,
		&i.PrimaryStorageKey,
		&i.PrimaryStorageProviderID,
		&i.PrimaryStorageProviderName,
		&i.PrimaryProviderType,
		&i.PrimaryBucket,
		&i.PrimaryRegion,
		&i.PrimaryEndpoint,
	)
	return i, err
}

const listMediaFilesByStatus = `-- name: ListMediaFilesByStatus :many
SELECT
    id,
    file_name,
    mime_type,
    size,
    checksum,
    status,
    uploaded_by,
    original_name,
    duration_ms,
    created_at
FROM media_files
WHERE status = $1
ORDER BY created_at DESC
LIMIT $3
OFFSET $2
`

type ListMediaFilesByStatusParams struct {
	Status     string
	PageOffset int32
	PageLimit  int32
}

func (q *Queries) ListMediaFilesByStatus(ctx context.Context, arg ListMediaFilesByStatusParams) ([]MediaFile, error) {
	rows, err := q.db.Query(ctx, listMediaFilesByStatus, arg.Status, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MediaFile
	for rows.Next() {
		var i MediaFile
		if err := rows.Scan(
			&i.ID,
			&i.FileName,
			&i.MimeType,
			&i.Size,
			&i.Checksum,
			&i.Status,
			&i.UploadedBy,
			&i.OriginalName,
			&i.DurationMs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOwnedMediaFiles = `-- name: ListOwnedMediaFiles :many
SELECT
    mf.id,
    mf.file_name,
    mf.mime_type,
    mf.size,
    mf.checksum,
    mf.status,
    mf.uploaded_by,
    mf.original_name,
    mf.duration_ms,
    mf.created_at
FROM media_files AS mf
INNER JOIN media_owners AS mo
    ON mo.media_id = mf.id
WHERE mo.owner_type = $1
  AND mo.owner_id = $2
ORDER BY mf.created_at DESC
LIMIT $4
OFFSET $3
`

type ListOwnedMediaFilesParams struct {
	OwnerType  string
	OwnerID    uuid.UUID
	PageOffset int32
	PageLimit  int32
}

func (q *Queries) ListOwnedMediaFiles(ctx context.Context, arg ListOwnedMediaFilesParams) ([]MediaFile, error) {
	rows, err := q.db.Query(ctx, listOwnedMediaFiles,
		arg.OwnerType,
		arg.OwnerID,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MediaFile
	for rows.Next() {
		var i MediaFile
		if err := rows.Scan(
			&i.ID,
			&i.FileName,
			&i.MimeType,
			&i.Size,
			&i.Checksum,
			&i.Status,
			&i.UploadedBy,
			&i.OriginalName,
			&i.DurationMs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUploadedMediaFiles = `-- name: ListUploadedMediaFiles :many
SELECT
    id,
    file_name,
    mime_type,
    size,
    checksum,
    status,
    uploaded_by,
    original_name,
    duration_ms,
    created_at
FROM media_files
WHERE uploaded_by = $1
ORDER BY created_at DESC
LIMIT $3
OFFSET $2
`

type ListUploadedMediaFilesParams struct {
	UploadedBy pgtype.UUID
	PageOffset int32
	PageLimit  int32
}

func (q *Queries) ListUploadedMediaFiles(ctx context.Context, arg ListUploadedMediaFilesParams) ([]MediaFile, error) {
	rows, err := q.db.Query(ctx, listUploadedMediaFiles, arg.UploadedBy, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MediaFile
	for rows.Next() {
		var i MediaFile
		if err := rows.Scan(
			&i.ID,
			&i.FileName,
			&i.MimeType,
			&i.Size,
			&i.Checksum,
			&i.Status,
			&i.UploadedBy,
			&i.OriginalName,
			&i.DurationMs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setMediaFileChecksum = `-- name: SetMediaFileChecksum :one
UPDATE media_files
SET checksum = $1
WHERE id = $2
RETURNING
    id,
    file_name,
    mime_type,
    size,
    checksum,
    status,
    uploaded_by,
    original_name,
    duration_ms,
    created_at
`

type SetMediaFileChecksumParams struct {
	Checksum pgtype.Text
	ID       uuid.UUID
}

func (q *Queries) SetMediaFileChecksum(ctx context.Context, arg SetMediaFileChecksumParams) (MediaFile, error) {
	row := q.db.QueryRow(ctx, setMediaFileChecksum, arg.Checksum, arg.ID)
	var i MediaFile
	err := row.Scan(
		&i.ID,
		&i.FileName,
		&i.MimeType,
		&i.Size,
		&i.Checksum,
		&i.Status,
		&i.UploadedBy,
		&i.OriginalName,
		&i.DurationMs,
		&i.CreatedAt,
	)
	return i, err
}

const updateMediaFileStatus = `-- name: UpdateMediaFileStatus :one
UPDATE media_files
SET status = $1
WHERE id = $2
RETURNING
    id,
    file_name,
    mime_type,
    size,
    checksum,
    status,
    uploaded_by,
    original_name,
    duration_ms,
    created_at
`

type UpdateMediaFileStatusParams struct {
	Status string
	ID     uuid.UUID
}

func (q *Queries) UpdateMediaFileStatus(ctx context.Context, arg UpdateMediaFileStatusParams) (MediaFile, error) {
	row := q.db.QueryRow(ctx, updateMediaFileStatus, arg.Status, arg.ID)
	var i MediaFile
	err := row.Scan(
		&i.ID,
		&i.FileName,
		&i.MimeType,
		&i.Size,
		&i.Checksum,
		&i.Status,
		&i.UploadedBy,
		&i.OriginalName,
		&i.DurationMs,
		&i.CreatedAt,
	)
	return i, err
}
