// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: media_external.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createExternalStorageAccount = `-- name: CreateExternalStorageAccount :one
INSERT INTO external_storage_accounts (
    id,
    partner_id,
    provider_type,
    bucket,
    region,
    endpoint
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING
    id,
    partner_id,
    provider_type,
    bucket,
    region,
    endpoint,
    created_at
`

type CreateExternalStorageAccountParams struct {
	ID           uuid.UUID
	PartnerID    uuid.UUID
	ProviderType string
	Bucket       string
	Region       pgtype.Text
	Endpoint     pgtype.Text
}

func (q *Queries) CreateExternalStorageAccount(ctx context.Context, arg CreateExternalStorageAccountParams) (ExternalStorageAccount, error) {
	row := q.db.QueryRow(ctx, createExternalStorageAccount,
		arg.ID,
		arg.PartnerID,
		arg.ProviderType,
		arg.Bucket,
		arg.Region,
		arg.Endpoint,
	)
	var i ExternalStorageAccount
	err := row.Scan(
		&i.ID,
		&i.PartnerID,
		&i.ProviderType,
		&i.Bucket,
		&i.Region,
		&i.Endpoint,
		&i.CreatedAt,
	)
	return i, err
}

const createMediaExternalObject = `-- name: CreateMediaExternalObject :one
INSERT INTO media_external_objects (
    media_id,
    account_id,
    external_url
)
VALUES (
    $1,
    $2,
    $3
)
RETURNING
    id,
    media_id,
    account_id,
    external_url,
    created_at
`

type CreateMediaExternalObjectParams struct {
	MediaID     uuid.UUID
	AccountID   pgtype.UUID
	ExternalUrl string
}

func (q *Queries) CreateMediaExternalObject(ctx context.Context, arg CreateMediaExternalObjectParams) (MediaExternalObject, error) {
	row := q.db.QueryRow(ctx, createMediaExternalObject, arg.MediaID, arg.AccountID, arg.ExternalUrl)
	var i MediaExternalObject
	err := row.Scan(
		&i.ID,
		&i.MediaID,
		&i.AccountID,
		&i.ExternalUrl,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMediaExternalObjectsByMediaID = `-- name: DeleteMediaExternalObjectsByMediaID :exec
DELETE FROM media_external_objects
WHERE media_id = $1
`

func (q *Queries) DeleteMediaExternalObjectsByMediaID(ctx context.Context, mediaID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMediaExternalObjectsByMediaID, mediaID)
	return err
}

const getExternalStorageAccountByID = `-- name: GetExternalStorageAccountByID :one
SELECT
    id,
    partner_id,
    provider_type,
    bucket,
    region,
    endpoint,
    created_at
FROM external_storage_accounts
WHERE id = $1
`

func (q *Queries) GetExternalStorageAccountByID(ctx context.Context, id uuid.UUID) (ExternalStorageAccount, error) {
	row := q.db.QueryRow(ctx, getExternalStorageAccountByID, id)
	var i ExternalStorageAccount
	err := row.Scan(
		&i.ID,
		&i.PartnerID,
		&i.ProviderType,
		&i.Bucket,
		&i.Region,
		&i.Endpoint,
		&i.CreatedAt,
	)
	return i, err
}

const listExternalStorageAccountsByPartnerID = `-- name: ListExternalStorageAccountsByPartnerID :many
SELECT
    id,
    partner_id,
    provider_type,
    bucket,
    region,
    endpoint,
    created_at
FROM external_storage_accounts
WHERE partner_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListExternalStorageAccountsByPartnerID(ctx context.Context, partnerID uuid.UUID) ([]ExternalStorageAccount, error) {
	rows, err := q.db.Query(ctx, listExternalStorageAccountsByPartnerID, partnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExternalStorageAccount
	for rows.Next() {
		var i ExternalStorageAccount
		if err := rows.Scan(
			&i.ID,
			&i.PartnerID,
			&i.ProviderType,
			&i.Bucket,
			&i.Region,
			&i.Endpoint,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMediaExternalObjectsByMediaID = `-- name: ListMediaExternalObjectsByMediaID :many
SELECT
    id,
    media_id,
    account_id,
    external_url,
    created_at
FROM media_external_objects
WHERE media_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListMediaExternalObjectsByMediaID(ctx context.Context, mediaID uuid.UUID) ([]MediaExternalObject, error) {
	rows, err := q.db.Query(ctx, listMediaExternalObjectsByMediaID, mediaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MediaExternalObject
	for rows.Next() {
		var i MediaExternalObject
		if err := rows.Scan(
			&i.ID,
			&i.MediaID,
			&i.AccountID,
			&i.ExternalUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
