// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: media_variants.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteMediaVariantsByMediaID = `-- name: DeleteMediaVariantsByMediaID :exec
DELETE FROM media_variants
WHERE media_id = $1
`

func (q *Queries) DeleteMediaVariantsByMediaID(ctx context.Context, mediaID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMediaVariantsByMediaID, mediaID)
	return err
}

const getMediaVariantByName = `-- name: GetMediaVariantByName :one
SELECT
    id,
    media_id,
    variant_name,
    storage_provider_id,
    storage_key,
    width,
    height,
    size,
    format,
    quality,
    status,
    created_at,
    updated_at
FROM media_variants
WHERE media_id = $1
  AND variant_name = $2
`

type GetMediaVariantByNameParams struct {
	MediaID     uuid.UUID
	VariantName string
}

func (q *Queries) GetMediaVariantByName(ctx context.Context, arg GetMediaVariantByNameParams) (MediaVariant, error) {
	row := q.db.QueryRow(ctx, getMediaVariantByName, arg.MediaID, arg.VariantName)
	var i MediaVariant
	err := row.Scan(
		&i.ID,
		&i.MediaID,
		&i.VariantName,
		&i.StorageProviderID,
		&i.StorageKey,
		&i.Width,
		&i.Height,
		&i.Size,
		&i.Format,
		&i.Quality,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMediaVariantsByMediaID = `-- name: ListMediaVariantsByMediaID :many
SELECT
    id,
    media_id,
    variant_name,
    storage_provider_id,
    storage_key,
    width,
    height,
    size,
    format,
    quality,
    status,
    created_at,
    updated_at
FROM media_variants
WHERE media_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListMediaVariantsByMediaID(ctx context.Context, mediaID uuid.UUID) ([]MediaVariant, error) {
	rows, err := q.db.Query(ctx, listMediaVariantsByMediaID, mediaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MediaVariant
	for rows.Next() {
		var i MediaVariant
		if err := rows.Scan(
			&i.ID,
			&i.MediaID,
			&i.VariantName,
			&i.StorageProviderID,
			&i.StorageKey,
			&i.Width,
			&i.Height,
			&i.Size,
			&i.Format,
			&i.Quality,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMediaVariantsByStatus = `-- name: ListMediaVariantsByStatus :many
SELECT
    id,
    media_id,
    variant_name,
    storage_provider_id,
    storage_key,
    width,
    height,
    size,
    format,
    quality,
    status,
    created_at,
    updated_at
FROM media_variants
WHERE status = $1
ORDER BY created_at ASC
LIMIT $3
OFFSET $2
`

type ListMediaVariantsByStatusParams struct {
	Status     string
	PageOffset int32
	PageLimit  int32
}

func (q *Queries) ListMediaVariantsByStatus(ctx context.Context, arg ListMediaVariantsByStatusParams) ([]MediaVariant, error) {
	rows, err := q.db.Query(ctx, listMediaVariantsByStatus, arg.Status, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MediaVariant
	for rows.Next() {
		var i MediaVariant
		if err := rows.Scan(
			&i.ID,
			&i.MediaID,
			&i.VariantName,
			&i.StorageProviderID,
			&i.StorageKey,
			&i.Width,
			&i.Height,
			&i.Size,
			&i.Format,
			&i.Quality,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMediaVariantStatus = `-- name: UpdateMediaVariantStatus :one
UPDATE media_variants
SET
    status = $1,
    updated_at = now()
WHERE id = $2
RETURNING
    id,
    media_id,
    variant_name,
    storage_provider_id,
    storage_key,
    width,
    height,
    size,
    format,
    quality,
    status,
    created_at,
    updated_at
`

type UpdateMediaVariantStatusParams struct {
	Status string
	ID     uuid.UUID
}

func (q *Queries) UpdateMediaVariantStatus(ctx context.Context, arg UpdateMediaVariantStatusParams) (MediaVariant, error) {
	row := q.db.QueryRow(ctx, updateMediaVariantStatus, arg.Status, arg.ID)
	var i MediaVariant
	err := row.Scan(
		&i.ID,
		&i.MediaID,
		&i.VariantName,
		&i.StorageProviderID,
		&i.StorageKey,
		&i.Width,
		&i.Height,
		&i.Size,
		&i.Format,
		&i.Quality,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertMediaVariant = `-- name: UpsertMediaVariant :one
INSERT INTO media_variants (
    media_id,
    variant_name,
    storage_provider_id,
    storage_key,
    width,
    height,
    size,
    format,
    quality,
    status
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
)
ON CONFLICT (media_id, variant_name)
DO UPDATE SET
    storage_provider_id = EXCLUDED.storage_provider_id,
    storage_key = EXCLUDED.storage_key,
    width = EXCLUDED.width,
    height = EXCLUDED.height,
    size = EXCLUDED.size,
    format = EXCLUDED.format,
    quality = EXCLUDED.quality,
    status = EXCLUDED.status,
    updated_at = now()
RETURNING
    id,
    media_id,
    variant_name,
    storage_provider_id,
    storage_key,
    width,
    height,
    size,
    format,
    quality,
    status,
    created_at,
    updated_at
`

type UpsertMediaVariantParams struct {
	MediaID           uuid.UUID
	VariantName       string
	StorageProviderID uuid.UUID
	StorageKey        string
	Width             pgtype.Int4
	Height            pgtype.Int4
	Size              pgtype.Int8
	Format            pgtype.Text
	Quality           pgtype.Int2
	Status            string
}

func (q *Queries) UpsertMediaVariant(ctx context.Context, arg UpsertMediaVariantParams) (MediaVariant, error) {
	row := q.db.QueryRow(ctx, upsertMediaVariant,
		arg.MediaID,
		arg.VariantName,
		arg.StorageProviderID,
		arg.StorageKey,
		arg.Width,
		arg.Height,
		arg.Size,
		arg.Format,
		arg.Quality,
		arg.Status,
	)
	var i MediaVariant
	err := row.Scan(
		&i.ID,
		&i.MediaID,
		&i.VariantName,
		&i.StorageProviderID,
		&i.StorageKey,
		&i.Width,
		&i.Height,
		&i.Size,
		&i.Format,
		&i.Quality,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
