// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: media_storage.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createMediaStorageObject = `-- name: CreateMediaStorageObject :one
INSERT INTO media_storage_objects (
    media_id,
    storage_provider_id,
    storage_key,
    is_primary
)
VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING
    id,
    media_id,
    storage_provider_id,
    storage_key,
    is_primary,
    created_at
`

type CreateMediaStorageObjectParams struct {
	MediaID           uuid.UUID
	StorageProviderID uuid.UUID
	StorageKey        string
	IsPrimary         bool
}

func (q *Queries) CreateMediaStorageObject(ctx context.Context, arg CreateMediaStorageObjectParams) (MediaStorageObject, error) {
	row := q.db.QueryRow(ctx, createMediaStorageObject,
		arg.MediaID,
		arg.StorageProviderID,
		arg.StorageKey,
		arg.IsPrimary,
	)
	var i MediaStorageObject
	err := row.Scan(
		&i.ID,
		&i.MediaID,
		&i.StorageProviderID,
		&i.StorageKey,
		&i.IsPrimary,
		&i.CreatedAt,
	)
	return i, err
}

const createStorageProvider = `-- name: CreateStorageProvider :one
INSERT INTO storage_providers (
    name,
    provider_type,
    endpoint,
    region,
    bucket,
    is_active,
    priority
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING
    id,
    name,
    provider_type,
    endpoint,
    region,
    bucket,
    is_active,
    priority,
    created_at
`

type CreateStorageProviderParams struct {
	Name         string
	ProviderType string
	Endpoint     pgtype.Text
	Region       pgtype.Text
	Bucket       string
	IsActive     bool
	Priority     int16
}

func (q *Queries) CreateStorageProvider(ctx context.Context, arg CreateStorageProviderParams) (StorageProvider, error) {
	row := q.db.QueryRow(ctx, createStorageProvider,
		arg.Name,
		arg.ProviderType,
		arg.Endpoint,
		arg.Region,
		arg.Bucket,
		arg.IsActive,
		arg.Priority,
	)
	var i StorageProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProviderType,
		&i.Endpoint,
		&i.Region,
		&i.Bucket,
		&i.IsActive,
		&i.Priority,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMediaStorageObjectsByMediaID = `-- name: DeleteMediaStorageObjectsByMediaID :exec
DELETE FROM media_storage_objects
WHERE media_id = $1
`

func (q *Queries) DeleteMediaStorageObjectsByMediaID(ctx context.Context, mediaID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMediaStorageObjectsByMediaID, mediaID)
	return err
}

const getPrimaryMediaStorageObjectByMediaID = `-- name: GetPrimaryMediaStorageObjectByMediaID :one
SELECT
    id,
    media_id,
    storage_provider_id,
    storage_key,
    is_primary,
    created_at
FROM media_storage_objects
WHERE media_id = $1
  AND is_primary = TRUE
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetPrimaryMediaStorageObjectByMediaID(ctx context.Context, mediaID uuid.UUID) (MediaStorageObject, error) {
	row := q.db.QueryRow(ctx, getPrimaryMediaStorageObjectByMediaID, mediaID)
	var i MediaStorageObject
	err := row.Scan(
		&i.ID,
		&i.MediaID,
		&i.StorageProviderID,
		&i.StorageKey,
		&i.IsPrimary,
		&i.CreatedAt,
	)
	return i, err
}

const getStorageProviderByID = `-- name: GetStorageProviderByID :one
SELECT
    id,
    name,
    provider_type,
    endpoint,
    region,
    bucket,
    is_active,
    priority,
    created_at
FROM storage_providers
WHERE id = $1
`

func (q *Queries) GetStorageProviderByID(ctx context.Context, id uuid.UUID) (StorageProvider, error) {
	row := q.db.QueryRow(ctx, getStorageProviderByID, id)
	var i StorageProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProviderType,
		&i.Endpoint,
		&i.Region,
		&i.Bucket,
		&i.IsActive,
		&i.Priority,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveStorageProviders = `-- name: ListActiveStorageProviders :many
SELECT
    id,
    name,
    provider_type,
    endpoint,
    region,
    bucket,
    is_active,
    priority,
    created_at
FROM storage_providers
WHERE is_active = TRUE
ORDER BY priority ASC, created_at ASC
`

func (q *Queries) ListActiveStorageProviders(ctx context.Context) ([]StorageProvider, error) {
	rows, err := q.db.Query(ctx, listActiveStorageProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StorageProvider
	for rows.Next() {
		var i StorageProvider
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ProviderType,
			&i.Endpoint,
			&i.Region,
			&i.Bucket,
			&i.IsActive,
			&i.Priority,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMediaStorageObjectsByMediaID = `-- name: ListMediaStorageObjectsByMediaID :many
SELECT
    id,
    media_id,
    storage_provider_id,
    storage_key,
    is_primary,
    created_at
FROM media_storage_objects
WHERE media_id = $1
ORDER BY is_primary DESC, created_at ASC
`

func (q *Queries) ListMediaStorageObjectsByMediaID(ctx context.Context, mediaID uuid.UUID) ([]MediaStorageObject, error) {
	rows, err := q.db.Query(ctx, listMediaStorageObjectsByMediaID, mediaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MediaStorageObject
	for rows.Next() {
		var i MediaStorageObject
		if err := rows.Scan(
			&i.ID,
			&i.MediaID,
			&i.StorageProviderID,
			&i.StorageKey,
			&i.IsPrimary,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPrimaryMediaStorageObject = `-- name: SetPrimaryMediaStorageObject :exec
WITH target AS (
    SELECT
        $1::uuid AS media_id,
        $2::uuid AS storage_object_id
)
UPDATE media_storage_objects AS mso
SET is_primary = (mso.id = target.storage_object_id)
FROM target
WHERE mso.media_id = target.media_id
`

type SetPrimaryMediaStorageObjectParams struct {
	MediaID         uuid.UUID
	StorageObjectID uuid.UUID
}

func (q *Queries) SetPrimaryMediaStorageObject(ctx context.Context, arg SetPrimaryMediaStorageObjectParams) error {
	_, err := q.db.Exec(ctx, setPrimaryMediaStorageObject, arg.MediaID, arg.StorageObjectID)
	return err
}
