// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: media_owners.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createMediaOwner = `-- name: CreateMediaOwner :one
INSERT INTO media_owners (
    media_id,
    owner_type,
    owner_id,
    field
)
VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING
    id,
    media_id,
    owner_type,
    owner_id,
    field,
    created_at,
    updated_at
`

type CreateMediaOwnerParams struct {
	MediaID   uuid.UUID
	OwnerType string
	OwnerID   uuid.UUID
	Field     pgtype.Text
}

func (q *Queries) CreateMediaOwner(ctx context.Context, arg CreateMediaOwnerParams) (MediaOwner, error) {
	row := q.db.QueryRow(ctx, createMediaOwner,
		arg.MediaID,
		arg.OwnerType,
		arg.OwnerID,
		arg.Field,
	)
	var i MediaOwner
	err := row.Scan(
		&i.ID,
		&i.MediaID,
		&i.OwnerType,
		&i.OwnerID,
		&i.Field,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMediaOwner = `-- name: DeleteMediaOwner :execrows
DELETE FROM media_owners
WHERE media_id = $1
  AND owner_type = $2
  AND owner_id = $3
`

type DeleteMediaOwnerParams struct {
	MediaID   uuid.UUID
	OwnerType string
	OwnerID   uuid.UUID
}

func (q *Queries) DeleteMediaOwner(ctx context.Context, arg DeleteMediaOwnerParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMediaOwner, arg.MediaID, arg.OwnerType, arg.OwnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteMediaOwnersByMediaID = `-- name: DeleteMediaOwnersByMediaID :exec
DELETE FROM media_owners
WHERE media_id = $1
`

func (q *Queries) DeleteMediaOwnersByMediaID(ctx context.Context, mediaID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMediaOwnersByMediaID, mediaID)
	return err
}

const listMediaOwnersByMediaID = `-- name: ListMediaOwnersByMediaID :many
SELECT
    id,
    media_id,
    owner_type,
    owner_id,
    field,
    created_at,
    updated_at
FROM media_owners
WHERE media_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListMediaOwnersByMediaID(ctx context.Context, mediaID uuid.UUID) ([]MediaOwner, error) {
	rows, err := q.db.Query(ctx, listMediaOwnersByMediaID, mediaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MediaOwner
	for rows.Next() {
		var i MediaOwner
		if err := rows.Scan(
			&i.ID,
			&i.MediaID,
			&i.OwnerType,
			&i.OwnerID,
			&i.Field,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
