// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: media_access_policies.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createMediaAccessPolicy = `-- name: CreateMediaAccessPolicy :one
INSERT INTO media_access_policies (
    media_id,
    visibility
)
VALUES (
    $1,
    $2
)
RETURNING
    id,
    media_id,
    visibility,
    created_at,
    updated_at
`

type CreateMediaAccessPolicyParams struct {
	MediaID    uuid.UUID
	Visibility string
}

func (q *Queries) CreateMediaAccessPolicy(ctx context.Context, arg CreateMediaAccessPolicyParams) (MediaAccessPolicy, error) {
	row := q.db.QueryRow(ctx, createMediaAccessPolicy, arg.MediaID, arg.Visibility)
	var i MediaAccessPolicy
	err := row.Scan(
		&i.ID,
		&i.MediaID,
		&i.Visibility,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMediaAccessPoliciesByMediaID = `-- name: DeleteMediaAccessPoliciesByMediaID :exec
DELETE FROM media_access_policies
WHERE media_id = $1
`

func (q *Queries) DeleteMediaAccessPoliciesByMediaID(ctx context.Context, mediaID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMediaAccessPoliciesByMediaID, mediaID)
	return err
}

const getLatestMediaAccessPolicyByMediaID = `-- name: GetLatestMediaAccessPolicyByMediaID :one
SELECT
    id,
    media_id,
    visibility,
    created_at,
    updated_at
FROM media_access_policies
WHERE media_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestMediaAccessPolicyByMediaID(ctx context.Context, mediaID uuid.UUID) (MediaAccessPolicy, error) {
	row := q.db.QueryRow(ctx, getLatestMediaAccessPolicyByMediaID, mediaID)
	var i MediaAccessPolicy
	err := row.Scan(
		&i.ID,
		&i.MediaID,
		&i.Visibility,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMediaAccessPoliciesByMediaID = `-- name: ListMediaAccessPoliciesByMediaID :many
SELECT
    id,
    media_id,
    visibility,
    created_at,
    updated_at
FROM media_access_policies
WHERE media_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListMediaAccessPoliciesByMediaID(ctx context.Context, mediaID uuid.UUID) ([]MediaAccessPolicy, error) {
	rows, err := q.db.Query(ctx, listMediaAccessPoliciesByMediaID, mediaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MediaAccessPolicy
	for rows.Next() {
		var i MediaAccessPolicy
		if err := rows.Scan(
			&i.ID,
			&i.MediaID,
			&i.Visibility,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMediaAccessPolicy = `-- name: UpdateMediaAccessPolicy :one
UPDATE media_access_policies
SET
    visibility = $1,
    updated_at = now()
WHERE id = $2
RETURNING
    id,
    media_id,
    visibility,
    created_at,
    updated_at
`

type UpdateMediaAccessPolicyParams struct {
	Visibility string
	ID         uuid.UUID
}

func (q *Queries) UpdateMediaAccessPolicy(ctx context.Context, arg UpdateMediaAccessPolicyParams) (MediaAccessPolicy, error) {
	row := q.db.QueryRow(ctx, updateMediaAccessPolicy, arg.Visibility, arg.ID)
	var i MediaAccessPolicy
	err := row.Scan(
		&i.ID,
		&i.MediaID,
		&i.Visibility,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
