// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ExternalStorageAccount struct {
	ID           uuid.UUID
	PartnerID    uuid.UUID
	ProviderType string
	Bucket       string
	Region       pgtype.Text
	Endpoint     pgtype.Text
	CreatedAt    pgtype.Timestamptz
}

type MediaAccessPolicy struct {
	ID         uuid.UUID
	MediaID    uuid.UUID
	Visibility string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type MediaExternalObject struct {
	ID          uuid.UUID
	MediaID     uuid.UUID
	AccountID   pgtype.UUID
	ExternalUrl string
	CreatedAt   pgtype.Timestamptz
}

type MediaFile struct {
	ID           uuid.UUID
	FileName     string
	MimeType     string
	Size         int64
	Checksum     pgtype.Text
	Status       string
	UploadedBy   pgtype.UUID
	OriginalName pgtype.Text
	DurationMs   pgtype.Int4
	CreatedAt    pgtype.Timestamptz
}

type MediaOwner struct {
	ID        uuid.UUID
	MediaID   uuid.UUID
	OwnerType string
	OwnerID   uuid.UUID
	Field     pgtype.Text
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type MediaStorageObject struct {
	ID                uuid.UUID
	MediaID           uuid.UUID
	StorageProviderID uuid.UUID
	StorageKey        string
	IsPrimary         bool
	CreatedAt         pgtype.Timestamptz
}

type MediaVariant struct {
	ID                uuid.UUID
	MediaID           uuid.UUID
	VariantName       string
	StorageProviderID uuid.UUID
	StorageKey        string
	Width             pgtype.Int4
	Height            pgtype.Int4
	Size              pgtype.Int8
	Format            pgtype.Text
	Quality           pgtype.Int2
	Status            string
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type StorageProvider struct {
	ID           uuid.UUID
	Name         string
	ProviderType string
	Endpoint     pgtype.Text
	Region       pgtype.Text
	Bucket       string
	IsActive     bool
	Priority     int16
	CreatedAt    pgtype.Timestamptz
}
